version: '3.5'

x-base: &backendbase
  env_file:
   - .env
  build:
    dockerfile: Dockerfile.local
    context: ./app

services:
  db:
    image: "postgres:12.2-alpine"
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/.pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: echo 'SELECT 1' | PGPASSWORD=$POSTGRES_PASSWORD psql --host $POSTGRES_HOST --user $POSTGRES_USER $POSTGRES_DB
      interval: 1m
      timeout: 10s
      retries: 3

  app:
    <<: *backendbase
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrate
      - collectstatic
    volumes:
      - ./app:/app
    healthcheck:
      test: curl --fail http://localhost:8000/admin/login/?healthcheck || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  migrate:
    <<: *backendbase
    command: sh entrypoints/migrate.sh
    restart: on-failure

  collectstatic:
    <<: *backendbase
    command: sh entrypoints/collectstatic.sh
    restart: on-failure
